overlay: Introduce /run/bin
See: https://github.com/coreos/fedora-coreos-tracker/issues/354

Basically we want to support things like containers that contain
binaries designed to execute on the host.  These should really
be "lifecycle bound" to the container image.  Let's at least
have an obvious place to drop them that goes away on reboot.

diff --git a/tests/kola/basic b/tests/kola/basic
--- a/tests/kola/basic
+++ b/tests/kola/basic
@@ -1,2 +1,10 @@
 #!/bin/bash
-exec systemctl is-enabled logrotate.service
+# Miscellaneous read-only/nondestructive tests.
+set -xeuo pipefail
+
+systemctl is-enabled logrotate.service
+
+if ! test -d /run/bin; then
+  echo "Missing /run/bin" 1>&2
+  exit 1
+fi
