tests/misc-ro: check for prjquota
By default, we mount XFS with the `prjquota` option. Verify this.

(cherry picked from commit b9dca277336fdb88ab565afd0962745eb64f8f09)

diff --git a/tests/kola/misc-ro b/tests/kola/misc-ro
--- a/tests/kola/misc-ro
+++ b/tests/kola/misc-ro
@@ -139,3 +139,9 @@ if [ $(systemctl is-enabled systemd-repart.service) != 'masked' ]; then
     fatal "systemd-repart.service systemd unit should be masked"
 fi
 ok "systemd-repart.service systemd unit is masked"
+
+rootflags=$(findmnt /sysroot -no OPTIONS)
+if ! grep prjquota <<< "${rootflags}"; then
+    fatal "missing prjquota in root mount flags: ${rootflags}"
+fi
+ok "root mounted with prjquota"
