ci: error out if downgrade detected
In the majority of cases, we don't expect new builds to downgrade RPMs.
Let's default to erroring out and contributors can consciously override
CI if was really expected.

diff --git a/.cci.jenkinsfile b/.cci.jenkinsfile
--- a/.cci.jenkinsfile
+++ b/.cci.jenkinsfile
@@ -50,6 +50,10 @@ cosaPod {
                 cd /srv/fcos
                 new_commit=\$(jq -r '.["ostree-commit"]' builds/latest/x86_64/meta.json)
                 rpm-ostree db diff --repo tmp/repo ${parent_commit} \${new_commit} | tee tmp/diff.txt
+                if grep -q Downgraded tmp/diff.txt; then
+                    echo "Downgrade detected. This is likely unintentional. If not, you may safely ignore this error."
+                    exit 1
+                fi
             """)
         }
     }
