overlay/live-generator: Don't error out if not on live ISO
Move up the check for being on a live image, and exit early
if we're not.  Fixes an error in the journal booting on qemu.
(We should have kola check for this)

Reported-by: @SerialVelocity

diff --git a/overlay.d/05core/usr/lib/dracut/modules.d/20live/live-generator b/overlay.d/05core/usr/lib/dracut/modules.d/20live/live-generator
--- a/overlay.d/05core/usr/lib/dracut/modules.d/20live/live-generator
+++ b/overlay.d/05core/usr/lib/dracut/modules.d/20live/live-generator
@@ -15,17 +15,19 @@ add_requires() {
     ln -sf "../${name}" "${requires_dir}/${name}"
 }
 
-isoroot=$(getarg coreos.liveiso=)
-if is-live-image; then
-    # Create stamp file that everything else should use to detect a live boot
-    > /run/ostree-live
+if ! is-live-image; then
+    exit 0
+fi
 
-    add_requires sysroot.mount
-    add_requires sysroot-etc.mount
-    add_requires sysroot-var.mount
+# Create stamp file that everything else should use to detect a live boot
+> /run/ostree-live
 
-    mkdir -p "${UNIT_DIR}/ostree-prepare-root.service.d"
-    cat > "${UNIT_DIR}/ostree-prepare-root.service.d/10-live.conf" <<EOF
+add_requires sysroot.mount
+add_requires sysroot-etc.mount
+add_requires sysroot-var.mount
+
+mkdir -p "${UNIT_DIR}/ostree-prepare-root.service.d"
+cat > "${UNIT_DIR}/ostree-prepare-root.service.d/10-live.conf" <<EOF
 # With live PXE there's no ostree= argument on the kernel command line, so
 # we need to find the tree path and pass it to ostree-prepare-root.  But
 # ostree-prepare-root only knows how to read the path from
@@ -43,9 +45,9 @@ ExecStartPre=/usr/sbin/ostree-cmdline start
 ExecStartPost=/usr/sbin/ostree-cmdline stop
 EOF
 
-    # In this case, the rootfs is directly in the initramfs
-    if [ -f /root.squashfs ]; then
-        cat >"${UNIT_DIR}/sysroot.mount" <<EOF
+# In this case, the rootfs is directly in the initramfs
+if [ -f /root.squashfs ]; then
+    cat >"${UNIT_DIR}/sysroot.mount" <<EOF
 # Automatically generated by live-generator
 
 [Unit]
@@ -57,10 +59,16 @@ What=/root.squashfs
 Where=/sysroot
 Type=squashfs
 EOF
-    else
-        # And in this case, it's on the ISO
-        mkdir -p /run/media/iso
-        cat >"${UNIT_DIR}/run-media-iso.mount" <<EOF
+else
+    isoroot=$(getarg coreos.liveiso=)
+    if [ -z "${isoroot}" ]; then
+        echo "Missing required coreos.liveiso kernel argument" 1>&2
+        exit 1
+    fi
+
+    # And in this case, it's on the ISO
+    mkdir -p /run/media/iso
+    cat >"${UNIT_DIR}/run-media-iso.mount" <<EOF
 # Automatically generated by live-generator
 
 [Unit]
@@ -73,7 +81,7 @@ Where=/run/media/iso
 Type=iso9660
 EOF
 
-        cat >"${UNIT_DIR}/sysroot.mount" <<EOF
+    cat >"${UNIT_DIR}/sysroot.mount" <<EOF
 # Automatically generated by live-generator
 
 [Unit]
@@ -86,9 +94,9 @@ What=/run/media/iso/root.squashfs
 Where=/sysroot
 Type=squashfs
 EOF
-    fi
+fi
 
-    cat >"${UNIT_DIR}/sysroot-etc.mount" <<EOF
+cat >"${UNIT_DIR}/sysroot-etc.mount" <<EOF
 # Automatically generated by live-generator
 [Unit]
 DefaultDependencies=false
@@ -111,7 +119,7 @@ Type=overlay
 Options=lowerdir=/sysroot/etc,upperdir=/writable/etc/upper,workdir=/writable/etc/work,redirect_dir=on,index=on,xino=on
 EOF
 
-    cat >"${UNIT_DIR}/sysroot-var.mount" <<EOF
+cat >"${UNIT_DIR}/sysroot-var.mount" <<EOF
 # Automatically generated by live-generator
 [Unit]
 DefaultDependencies=false
@@ -133,4 +141,3 @@ Where=/sysroot/var
 Type=none
 Options=bind
 EOF
-fi
