tree: promote changes from testing-devel at 7be06b3f0889e6a89e6b897f425321d2bbb46d6b

diff --git a/overlay.d/05core/usr/lib/dracut/modules.d/20live/live-generator b/overlay.d/05core/usr/lib/dracut/modules.d/20live/live-generator
--- a/overlay.d/05core/usr/lib/dracut/modules.d/20live/live-generator
+++ b/overlay.d/05core/usr/lib/dracut/modules.d/20live/live-generator
@@ -2,6 +2,8 @@
 # -*- mode: shell-script; indent-tabs-mode: nil; sh-basic-offset: 4; -*-
 # ex: ts=8 sw=4 sts=4 et filetype=sh
 
+command -v getarg >/dev/null || . /usr/lib/dracut-lib.sh
+
 set -e
 
 UNIT_DIR="${1:-/tmp}"
@@ -13,16 +15,19 @@ add_requires() {
     ln -sf "../${name}" "${requires_dir}/${name}"
 }
 
-if [ -e /root.squashfs ]; then
-    # Create stamp file that everything else should use to detect a live boot
-    > /run/ostree-live
+if ! is-live-image; then
+    exit 0
+fi
 
-    add_requires sysroot.mount
-    add_requires sysroot-etc.mount
-    add_requires sysroot-var.mount
+# Create stamp file that everything else should use to detect a live boot
+> /run/ostree-live
 
-    mkdir -p "${UNIT_DIR}/ostree-prepare-root.service.d"
-    cat > "${UNIT_DIR}/ostree-prepare-root.service.d/10-live.conf" <<EOF
+add_requires sysroot.mount
+add_requires sysroot-etc.mount
+add_requires sysroot-var.mount
+
+mkdir -p "${UNIT_DIR}/ostree-prepare-root.service.d"
+cat > "${UNIT_DIR}/ostree-prepare-root.service.d/10-live.conf" <<EOF
 # With live PXE there's no ostree= argument on the kernel command line, so
 # we need to find the tree path and pass it to ostree-prepare-root.  But
 # ostree-prepare-root only knows how to read the path from
@@ -40,6 +45,8 @@ ExecStartPre=/usr/sbin/ostree-cmdline start
 ExecStartPost=/usr/sbin/ostree-cmdline stop
 EOF
 
+# In this case, the rootfs is directly in the initramfs
+if [ -f /root.squashfs ]; then
     cat >"${UNIT_DIR}/sysroot.mount" <<EOF
 # Automatically generated by live-generator
 
@@ -52,8 +59,44 @@ What=/root.squashfs
 Where=/sysroot
 Type=squashfs
 EOF
+else
+    isoroot=$(getarg coreos.liveiso=)
+    if [ -z "${isoroot}" ]; then
+        echo "Missing required coreos.liveiso kernel argument" 1>&2
+        exit 1
+    fi
 
-    cat >"${UNIT_DIR}/sysroot-etc.mount" <<EOF
+    # And in this case, it's on the ISO
+    mkdir -p /run/media/iso
+    cat >"${UNIT_DIR}/run-media-iso.mount" <<EOF
+# Automatically generated by live-generator
+
+[Unit]
+DefaultDependencies=false
+Before=initrd-root-fs.target
+
+[Mount]
+What=/dev/disk/by-label/${isoroot}
+Where=/run/media/iso
+Type=iso9660
+EOF
+
+    cat >"${UNIT_DIR}/sysroot.mount" <<EOF
+# Automatically generated by live-generator
+
+[Unit]
+DefaultDependencies=false
+Before=initrd-root-fs.target
+Requires=run-media-iso.mount
+
+[Mount]
+What=/run/media/iso/root.squashfs
+Where=/sysroot
+Type=squashfs
+EOF
+fi
+
+cat >"${UNIT_DIR}/sysroot-etc.mount" <<EOF
 # Automatically generated by live-generator
 [Unit]
 DefaultDependencies=false
@@ -76,7 +119,7 @@ Type=overlay
 Options=lowerdir=/sysroot/etc,upperdir=/writable/etc/upper,workdir=/writable/etc/work,redirect_dir=on,index=on,xino=on
 EOF
 
-    cat >"${UNIT_DIR}/sysroot-var.mount" <<EOF
+cat >"${UNIT_DIR}/sysroot-var.mount" <<EOF
 # Automatically generated by live-generator
 [Unit]
 DefaultDependencies=false
@@ -98,4 +141,3 @@ Where=/sysroot/var
 Type=none
 Options=bind
 EOF
-fi
